export enum Role {
  USER = 'USER',
  REVIEWER = 'REVIEWER',
  ADMIN = 'ADMIN',
  UNASSIGNED = '',
}

export enum NotificationType {
  CONNECTION_REQUEST_PENDING = 'CONNECTION_REQUEST_PENDING',
  CONNECTION_REQUEST_ACCEPTED = 'CONNECTION_REQUEST_ACCEPTED',
  PAYMENT_ACKNOWLEDGEMENT = 'PAYMENT_ACKNOWLEDGEMENT',
}
