import { useState } from 'react';
import { BsChevronDown, BsChevronLeft } from 'react-icons/bs';
import Switch from '../Switch';
import { TRootState, updateSetting, useUpdateSettingsMFAMutation } from '../../../state/store';
import { useDispatch, useSelector } from 'react-redux';

const MultiFactorAuthentication = () => {
  const dispatch = useDispatch();
  const [updateSettingsMFA] = useUpdateSettingsMFAMutation();
  const { user, token } = useSelector((store: TRootState) => store.user);
  const { setting } = useSelector((store: TRootState) => store.setting);
  const [isOptionShowing, setIsOptionShowing] = useState(false);

  const toggleOption = () => {
    setIsOptionShowing((prevState) => !prevState);
  };

  const handleSwitchToggled = (toggled: boolean) => {
    updateSettingsMFA({ mfaEnabled: toggled, token, settingId: user.settingId })
      .unwrap()
      .then(({ mfaEnabled }) => {
        dispatch(updateSetting({ ...setting, mfaEnabled }));
      });
  };

  return (
    <section className="my-20">
      <div className="flex justify-between">
        <div>
          <p className="font-bold text-gray-400">2FA</p>
          <p className="text-sm">Two Factor Authentication</p>
        </div>
        <div className="md:block hidden">
          <p>
            Add an extra layer of{' '}
            <span onClick={toggleOption} className="font-bold text-green-400 cursor-pointer">
              security
            </span>{' '}
            to block unauthorized access and protect your account.
          </p>
        </div>
        <div onClick={toggleOption} className="text-gray-400 cursor-pointer">
          {isOptionShowing ? <BsChevronDown /> : <BsChevronLeft />}
        </div>
      </div>
      {isOptionShowing && (
        <div className="my-8 animate-slidedown">
          <div className="flex justify-between items-center">
            <div>
              <div className="flex items-center">
                <h3>Authenticator app code</h3>
                <p className="ml-1 text-sm">(Recommended)</p>
              </div>
              <p className="text-sm">Enter a code generated by your authenticator app to confirm it’s you.</p>
            </div>
            <Switch switchToggled={setting.mfaEnabled} handleSwitchToggled={handleSwitchToggled} />
          </div>
        </div>
      )}
    </section>
  );
};

export default MultiFactorAuthentication;
