package com.hart.overwatch.notification;


public enum NotificationType {
    CONNECTION_REQUEST_PENDING, CONNECTION_REQUEST_ACCEPTED, PAYMENT_ACKNOWLEDGEMENT, REVIEW_INCOMPLETE, REVIEW_INPROGRESS, REVIEW_COMPLETED, COMMENT_REPLY

}
