ALTER SEQUENCE activity_sequence RESTART WITH 1;
ALTER SEQUENCE workspace_sequence RESTART WITH 1;
ALTER SEQUENCE todo_list_sequence RESTART WITH 1;
ALTER SEQUENCE todo_card_sequence RESTART WITH 1;
ALTER SEQUENCE profile_sequence RESTART WITH 1;
ALTER SEQUENCE _user_sequence RESTART WITH 1;

