CREATE SEQUENCE IF NOT EXISTS workspace_sequence START WITH 1 INCREMENT BY 1;
ALTER SEQUENCE workspace_sequence RESTART WITH 1;

CREATE SEQUENCE IF NOT EXISTS _user_sequence START WITH 1 INCREMENT BY 1;
ALTER SEQUENCE _user_sequence RESTART WITH 1;
