ALTER SEQUENCE team_comment_sequence RESTART WITH 1;
ALTER SEQUENCE team_post_sequence RESTART WITH 1;
ALTER SEQUENCE team_sequence RESTART WITH 1;
ALTER SEQUENCE profile_sequence RESTART WITH 1;
ALTER SEQUENCE _user_sequence RESTART WITH 1;

