ALTER SEQUENCE comment_vote_sequence RESTART WITH 1;
ALTER SEQUENCE comment_sequence RESTART WITH 1;
ALTER SEQUENCE profile_sequence RESTART WITH 1;
ALTER SEQUENCE _user_sequence RESTART WITH 1;
ALTER SEQUENCE tag_sequence RESTART WITH 1;
ALTER SEQUENCE topic_sequence RESTART WITH 1;

